---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions: 0